services:
  # FastAPI Application Service
  app:
    build: .
    container_name: lost_found_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - DB_HOST=lnf-db.c20rmtyx8ttq.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=LnF-password
      - DB_NAME=lnf-db
      - DB_PORT=3306
    networks:
      - lost_found_network

networks:
  lost_found_network:
    driver: bridge
